### PR TITLE
Ap 4428

### PR DESCRIPTION
**Pull request by alimfree**
Updated to use Apruve API version 4. Also bumped ruby and json gem versions. Swapped out red favicon for blue one.

### CODE REVIEW

**Comment by tcochran317** [comment]
:+1:

**Comment by CullenShane** [comment]
Looks good, have you completed a test checkout? :+1:

**Comment by alimfree** [comment]
Yep, I didn't try the corporate account. I did charge it to an employer.

**Comment by CullenShane** [comment]
:+1:

**Pull request merged**
